In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# 1)GRADED

In [4]:


# (a) Using a for loop, iterate through the list x
# and print an item if its divisible by 2 and less than 6
# (b) Using a for loop, iterate through the dictionary y
# and print a single string of the form "company, ceo"
# e.g. "CEO: Apple, Name: Tim Cook" will be the third entry
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = {
'Satya Nadella': 'Microsoft',
'Jeff Bezos': 'Amazon',
'Tim Cook': 'Apple'
}

print("\n a).Iterate through the list x ",*[i  for i in x if(i%2==0 and i<6)],sep='\n')

print("\n b).print a single string of the form 'company, ceo'\n",*['CEO: %s, Name: %s'%(i[1],i[0]) for i in y.items()],sep='\n')


 a).Iterate through the list x 
2
4

 b).print a single string of the form 'company, ceo'

CEO: Microsoft, Name: Satya Nadella
CEO: Amazon, Name: Jeff Bezos
CEO: Apple, Name: Tim Cook


# 2)GRADED


In [5]:
# Provided below are functions that are completely defined (add_numbers),
# partially defined (sub_numbers) and not defined (mult_numbers)
# (a) Complete sub_numbers so that it return difference of two numbers
# (b) Write a function called mult_numbers to multiply two numbers
sub_number = lambda num1,num2:abs(num1-num2)
mult_numbers = lambda num1,num2:num1*num2

print("\n a).sub_number:",sub_number(int(input("Enter num 1:")),int(input("Enter num 2:"))))
print("\n b).mult_numbers: ",mult_numbers(int(input("Enter num 1:")),int(input("Enter num 2:"))))


Enter num 1:4
Enter num 2:3

 a).sub_number: 1
Enter num 1:3
Enter num 2:0

 b).mult_numbers:  0


# 3)GRADED

In [6]:

# (a) Determine the shape, number of dimensions and type of
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr = np.arange(15).reshape(3, 5)
print("\n arr :\n",arr)
print("\n a). Determine the shape, number of dimensions and type of elements in the numpy array arr \n shape: %s ,number of dimensions: %s, type: %s"%(arr.shape,arr.ndim,arr.dtype))
print("\n b). Sum: ",np.sum(arr))
print("\n c). Mean: ",np.mean(arr))
print("\n d). Zeros:\n",np.zeros(arr.shape))
print("\n e). Ones:\n",np.ones(arr.shape))
print("\n f). Square:\n",np.square(arr))
print("\n g). Multiplication:\n",np.dot(arr,arr.T))





 arr :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

 a). Determine the shape, number of dimensions and type of elements in the numpy array arr 
 shape: (3, 5) ,number of dimensions: 2, type: int32

 b). Sum:  105

 c). Mean:  7.0

 d). Zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 e). Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 f). Square:
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]

 g). Multiplication:
 [[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


# 4)GRADED

In [7]:

# The following piece of code creates a DataFrame
# (a) Determine the shape of the dataframe

# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe

# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'

# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width

df = pd.read_csv('datasets_19_420_Iris.csv')
print(df.head(10))
print("\n a). Shape:",df.shape)
print("\n b). Columns: ",*[i+',' for i in df.columns])
print("\n c). 3rd Element:\n",df.iloc[2])
print("\n d). average of 'petal_width' where species is 'virginica' :",df.loc[df.Species=='Iris-virginica']["PetalWidthCm"].mean())
print("\n e). average of 'sepal_width' where species is 'setosa' :",df.loc[df.Species=='Iris-setosa']["SepalWidthCm"].max())
print("\n f). average value of sepal_length: ",df['SepalLengthCm'].mean())
print("\n g). average value of sepal_width: ",df['SepalWidthCm'].max())
print("\n h). average value of petal_width: ",df['PetalWidthCm'].min())


   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

 a). Shape: (150, 6)

 b). Columns:  Id, SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species,

 c). 3rd Element:
 Id                      